### ISSUE TITLE
撰写 readme

### ISSUE THREAD

**Issue by yankay** [DaoCloud/kube-node-tuning#6]
更完善一些

**Comment by creat2012-v2** [comment]
通过readme，没大明白这个project的功能。
有更加详细的项目文档可以分享么？

**Comment by creat2012-v2** [comment]
> 

所以，可以把他理解为，对node的调优？
可以理解为是人工、手动的进行对node调优？

**Comment by creat2012-v2** [comment]
> > > 
> > 
> > 
> > 所以，可以把他理解为，对node的调优？ 可以理解为是人工、手动的进行对node调优？
> 
> 是的。手动调优服务器上的 内核配置。

OK，明白！ 感谢解答。
